export enum ResourceType {
  Metal = "Metal",
  Plutonium = "Plutonium",
}

export enum ProbeState {
  Idle = "Idle",
  MiningMetal = "Mining Metal",
  MiningPlutonium = "Mining Plutonium",
  Traveling = "Traveling",
  Replicating = "Replicating",
  Scanning = "Scanning",
  Exploring = "Exploring",
  Researching = "Researching",
}

export enum AutonomyState {
  Idle = "Idle", // Waiting/Thinking
  GatheringFuel = "Fueling", // Mining Plutonium for travel
  GatheringMats = "Gathering", // Mining resources for replication
  ReadyToLaunch = "Ready", // Pre-flight check
}

export enum ProbeModel {
  MarkI = "Mark I",
  MarkII = "Mark II", // Faster flight, better sensors
  MarkIII = "Mark III", // Faster mining
  VonNeumannPrime = "Von Neumann Prime", // Fast replication, best sensors
}

export interface Coordinates {
  x: number;
  y: number;
}

export interface SolarSystem {
  id: string;
  name: string;
  position: Coordinates;
  visited: boolean;
  analyzed: boolean;
  discovered: boolean; // Fog of War status
  lore?: string; // Generated by Gemini
  resources: {
    [ResourceType.Metal]: number; // Abundance 0-100
    [ResourceType.Plutonium]: number; // Abundance 0-100
  };
  resourceYield: {
    [ResourceType.Metal]: number; // Total available
    [ResourceType.Plutonium]: number; // Total available
  };
  scienceRemaining?: number; // Finite science pool remaining in this system
  scienceTotal?: number; // Original total science for display/analytics
}

export interface ProbeStats {
  miningSpeed: number;
  flightSpeed: number;
  replicationSpeed: number;
  scanRange: number; // Light Years
  scanSpeed: number; // Multiplier
  autonomyLevel: number; // 0=Manual, 1=Adventurer, 2=Replicator
}

export interface ProbeBlueprint {
  id: string;
  name: string;
  stats: ProbeStats;
  cost: {
    Metal: number;
    Plutonium: number;
    time: number;
  };
  isCustom: boolean;
  initialInventory?: {
    [ResourceType.Metal]: number;
    [ResourceType.Plutonium]: number;
  };
}

export interface Probe {
  id: string;
  name: string;
  model: string; // Changed from ProbeModel enum to string to support custom names
  state: ProbeState;
  aiState?: AutonomyState; // Internal state for autonomous probes
  locationId: string | null; // System ID if docked
  originSystemId?: string; // The system where this probe was created
  lastScannedSystemId?: string; // The last system ID where a full scan was performed
  position: Coordinates; // Current coordinates (if flying)
  targetSystemId: string | null; // If flying
  heading?: number; // 0-360 degrees for Exploration
  lastSafetyCheck?: number; // Timestamp for throttling safety calculations
  lastDiversionCheck?: number; // Timestamp for throttling AI target acquisition
  inventory: {
    [ResourceType.Metal]: number;
    [ResourceType.Plutonium]: number;
  };
  stats: ProbeStats;
  progress: number; // 0-100 for current action
  miningBuffer: number; // Accumulator for smooth mining progress (0.0 to 1.0)
  pendingBlueprint?: ProbeBlueprint; // Blueprint being constructed if Replicating
  isSolarSailing?: boolean; // If true, traveling at reduced speed due to lack of fuel
  isAutonomyEnabled?: boolean; // User toggle for AI behavior
  researchBuffer?: number; // Accumulator for science collection
}

export interface GameState {
  systems: SolarSystem[];
  probes: Probe[];
  blueprints: ProbeBlueprint[]; // Available designs
  generatedSectors: Set<string>; // Track which spatial sectors have been generated
  isDesignerOpen: boolean; // UI State
  editingBlueprint?: ProbeBlueprint; // The blueprint currently being edited
  selectedProbeId: string | null;
  selectedSystemId: string | null;
  logs: string[];
  science: number; // Global science bank
  purchasedUnlocks: string[]; // IDs of purchased science unlocks
  maxStatLevelOverrides: Partial<Record<keyof ProbeStats, number>>; // Dynamic max levels from unlocks
}
